src/main/scripts/src/app.module.ts, src/main/scripts/src/components/common/tag-input/filter-save.component.html, src/main/scripts/src/components/common/tag-input/filter-save.component.scss, src/main/scripts/src/components/common/tag-input/filter.component.ts, src/main/scripts/src/components/views/pick_item/pick-item.component.html, src/main/scripts/src/components/views/pick_item/pick-item.component.scss, src/main/scripts/src/components/views/pick_item/pick-item.component.ts, src/main/scripts/src/components/views/research/document-info.component.html, src/main/scripts/src/components/views/research/document-info.component.scss, src/main/scripts/src/components/views/research/research.component.html, src/main/scripts/src/components/views/research/research.component.scss, src/main/scripts/src/components/views/research/research.component.ts, src/main/scripts/src/components/views/views.module.ts, src/main/scripts/src/services/document-navigation.service.ts, src/main/scripts/src/styles/basic.scss, src/main/scripts/src/viewport/top-panel.component.html, src/main/scripts/src/viewport/top-panel.component.scss, src/main/scripts/src/viewport/top-panel.component.ts, src/main/scripts/src/viewport/viewport.component.html, src/main/scripts/src/viewport/viewport.component.scss, src/main/scripts/src/viewport/viewport.component.ts
As I was speaking with Martin it turns out that our navigation was quite hard to understand, so we came up with this new way.
This is starting point for whole application, later it will be replaced with filter over all items (including views, collections and links)
Here was small bug where it forgot filtered items
It will remeber filtered items now
=> New navigation

src/main/scripts/webpack.config.js
Webpack proxy has been enabled, this helps us to combine UI with engine much easily.
1) If you want to test it locally run lumeer engine on wildfly
2) Run lumeer UI `npm start` in `src/main/srcipts`
Requests can be now made by calling `/lumeer-engine/*` webpack proxy will redirect the request to `http://localhost:8080/lumeer-engine/*`
Both `lumeer-engine` and `ui` has to be on same server, requests will be handled by server itself.
There might be problems with keycloak in UI, this can be avoided by adding `"disabled": true` in `src/main/scripts/webapp/WEB-INF/keycloak.json`
=> Proxy server

src/main/scripts/package.json, src/main/scripts/src/app.module.ts, src/main/scripts/src/components/common/common-components.module.ts, src/main/scripts/src/components/views/views.module.ts, src/main/scripts/src/vendor.ts
There is a warning when installing the project with `angular2-perfect-scrollbar` so I have updated it to the latest version `ngx-perfect-scrollbar` which supports Angular 4.
The same problem is with `angular2-drag-scroll`, however, I have not been able to find a new version of this library for Angular 4.
=> Update Angular Perfect Scrollbar dependency

src/main/scripts/src/boot.ts
When there is any UI error, application is constantly reloading.
this change should not effect any kind of data leak, since the application is not bootstrapped at all.
=> Do not reload if any UI error occurs

src/main/scripts/webpack.config.js
When the sourcecode is build using `npm run-script build` html loader is no longer breaking templates with removing quotes. This can be checked by running `npm run-script build` and observing `dist/js/app.bundle.js` file.
=> Change webpack config to use correctly HTML loader and do not break templates

src/main/scripts/package.json, src/main/scripts/src/app/app.module.ts, src/main/scripts/src/app/core/rest/collection.service.ts, src/main/scripts/src/app/core/rest/document.service.ts, src/main/scripts/src/app/core/rest/organization.service.ts, src/main/scripts/src/app/core/rest/project.service.ts, src/main/scripts/src/app/core/rest/roles.service.ts, src/main/scripts/src/app/core/rest/search.service.ts, src/main/scripts/src/app/core/rest/user-settings.service.ts, src/main/scripts/src/app/custom-typings.d.ts, src/main/scripts/src/services/keycloak.service.ts, src/main/scripts/webpack.config.js
This will enable to parametrize build so we can pass environment variables to our application.
To switch between different types of build process. LUMEER_ENV is always set to development for local changes (no need to change it locally). Also, if this variable is not set production mode is enabled.
To set engine URL prefix, default value is `lumeer-engine`.
=> Env variables

src/main/scripts/src/app/core/rest/organization.service.ts, src/main/scripts/src/app/core/rest/project.service.ts, src/main/scripts/src/app/core/rest/user-settings.service.ts
Services were returning `null` instead of an `Response`
So it's possible to check response status code until the backend services are refactored to return responses even for `put`, `post` and `delete`.
=> Fix services not returning HTTP response

src/main/scripts/tsconfig.json
@kubedo8, we will be able to use new functionality such as [Array.includes()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) now.
=> Enable ECMAScript 2017 constructs

src/main/scripts/package.json, src/main/scripts/src/app/core/rest/collection.service.ts, src/main/scripts/src/template-index.ejs
I also had to:
* Fix return types of service methods.
* Update to newer RxJS with fixed type problems.
We will be able to take full advantage of [new TypeScript features](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html) such as String Enums, etc.
=> Update to TypeScript 2.4

src/main/scripts/src/app/core/core.module.ts, src/main/scripts/src/app/core/keycloak/keycloak-http.service.ts, src/main/scripts/src/app/core/keycloak/keycloak.service.ts
When we were migrating from old app file structure we forgot to include `keycloak-http.service.ts` and `keycloak.service.ts` and put them in providers field. It caused that HTTP request had no JWT and keycloak refused it's request.
=> Add http and keycloak providers

src/main/scripts/src/app/core/core.module.ts, src/main/scripts/src/app/core/keycloak/keycloak-http.service.ts, src/main/scripts/src/app/core/keycloak/keycloak.service.ts, src/main/scripts/src/boot.ts
When we moved to newer version of angular Http interceptors were replaced by HttpClient, so we have to use newer way of intercepting our Authentication.
Please bear in mind that KC header is:
```
Authorization:Bearer JWT_TOKEN
```
=> Use Http interceptor based on HttpClient

src/main/scripts/src/app/shared/utils/query-converter.ts
Calling map and filter on `collectionCodes` and `filters` caused errors
=> Fix error on pages without query

src/main/scripts/src/app/core/core.module.ts, src/main/scripts/src/app/core/dto/user.settings.ts, src/main/scripts/src/app/core/home.component.ts, src/main/scripts/src/app/core/user-settings.service.ts, src/main/scripts/src/app/workspace/workspace-chooser/workspace-chooser.component.ts
The last selected organization and project is stored in the browser using Web Storage API so users do not have to select their workspace every time they open the application.
=> Store default project in browser #LMR-383

src/main/webapp/WEB-INF/web.xml
`index.html` is now used as an error page so the direct application URLs will work even when the application is running in WildFly AS.
The other nice thing about this is that our custom 404 page is shown (instead of blank `Not found` page provided by WildFly) when the given URL does not exist (within Angular routes).
=> Fix direct URL access on server #LMR-494

src/app/core/rest/group.service.ts, src/app/core/rest/link-instance.service.ts, src/app/core/rest/link-type.service.ts, src/app/core/rest/template.service.ts, src/app/core/rest/view.service.ts
The data records are now stored in their own workspace instead of all of them being together. This fixes some random errors when collections from links did not exist because they were from different project.
=> Fix scope of webstorage-based services #LMR-524

src/app/view/perspectives/post-it/post-it-perspective.component.ts, src/app/view/perspectives/post-it/util/selection-helper.ts
The `firstPostIt` is there just in case postIts were shuffled during user ordering.
=> ui/w/$ORG/$PROJ/view/postit - show frame on first arrow key press #LMR-597

src/app/app.initializer.ts
App was loading twice because keycloak did authorisation process after app initialisation
Added token fetching before angular app is initialised, so app should not load twice. That also seems to fix error in setUpGoogleAnalytics method in app.component
=> [LMR-655] Fix

src/app/core/rest/collection.service.ts, src/app/core/rest/document.service.ts, src/app/core/rest/home-page.service.ts, src/app/core/rest/organization.service.ts, src/app/core/rest/project.service.ts, src/app/core/rest/search.service.ts, src/app/core/store/collections/collections.effects.ts, src/app/core/store/documents/documents.effects.ts, src/app/core/store/groups/groups.effects.ts, src/app/core/store/link-instances/link-instances.effects.ts, src/app/core/store/link-types/link-types.effects.ts, src/app/core/store/notifications/notifications.effects.ts, src/app/core/store/organizations/organizations.effects.ts, src/app/core/store/projects/projects.effects.ts, src/app/core/store/router/router.effects.ts, src/app/core/store/smartdoc/smartdoc.effects.ts, src/app/core/store/tables/tables.effects.ts, src/app/core/store/users/users.effects.ts, src/app/core/store/views/views.effects.ts, src/app/shared/search-box/input/suggestions/search-suggestions.component.ts, src/app/workspace/organization/organization-settings.guard.ts, src/app/workspace/workspace.service.ts
We should never use `switchMap` operator when calling remote services. See [this article](https://blog.angularindepth.com/switchmap-bugs-b6de69155524) for more details.
=> Fix aborting REST API requests #LMR-795

src/app/app-routing.module.ts, src/app/core/store/app.state.ts, src/app/core/store/navigation/navigation.reducer.ts, src/app/core/store/router/lumeer-router-state-serializer.ts
Have you ever wondered why Redux DevTools are often freezing? Here is the answer:
Angular router classes create a complicated hierarchies with many cyclic references. Redux DevTools always try to serialize the content of the store and they go into the depth. The result was 2GB RAM taken by Redux DevTools and the eventual crash of the extension.
See [this NgRx issue](https://github.com/ngrx/platform/issues/97) and [this section of the documention](https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer).
=> Fix Redux DevTools freezing #LMR-797

angular.json, src/app/shared/pipes/permissions.pipe.ts, src/app/shared/pipes/pipes.module.ts, src/app/shared/post-it-collections/post-it-collections.component.html, src/app/shared/post-it-collections/post-it-collections.component.ts, src/app/shared/post-it-collections/post-it-collections.module.ts, src/app/shared/preview-results/preview-results.component.html, src/app/shared/preview-results/preview-results.component.ts, src/app/shared/preview-results/preview-results.module.ts, src/app/shared/utils/resource.utils.ts, src/app/view/perspectives/detail/detail-perspective.component.html, src/app/view/perspectives/detail/detail-perspective.component.ts
I am introducing a brand new `PermissionsPipe` which will simplify checking access rights in the templates and reduce the amount of code you need to write.
I have already refactored some components using this pipe so you can see how to use it.
There are still some places where it can be used but they will require more complex refactoring and I didn't want to do that in this PR. Document post-its perspective is one example of such a place.
=> Add permissions pipe #LMR-958

angular.json
The initial page of the application should now load only around 2.5 MB of JavaScript files.
=> Optimize scripts bundle size #LMR-959

src/app/shared/top-panel/top-panel.component.html, src/app/shared/top-panel/top-panel.component.scss, src/app/shared/top-panel/top-panel.component.ts, src/app/view/view-controls/view-controls.component.html, src/app/view/view-controls/view-controls.component.scss
The application should now fit into the screen of the smallest devices (e.g. iPhone SE).
However, it is not an ideal solution since a lot of vertical space is covered just by control panels. In the future, we will need to put all these controls into a dropdown menu which will only be shown on mobile devices.
=> Fix view controls on mobile devices #LMR-1047

src/app/view/perspectives/table/body/rows/table-rows.component.ts
This should also fix problem we see in Sentry as `Cannot read property 'children' of undefined`.
However, it does not move cursor to the next line when you create a new document in a table.
=> Do not move cursor on new document added to table #LMR-1056

.travis.yml, travis.sh
Do not run `ng build` and instead start the application with AOT compiler in order to speed up the whole Travis build process and catch all AOT compilation errors as before.
=> Do not build UI twice in Travis #LMR-1164

src/app/shared/pipes/permissions/link-instance-permissions.pipe.ts, src/app/view/perspectives/table/body/rows/cell-group/data-cell/table-data-cell.component.ts
I have switched checking link instance permissions from using its documents permissions to using its link type permissions. It should behave the same way since at the end only collection permissions are checked. 
The way it was implemented before prevented editing of link attribute column in uninitialized linked table row. Because table creates link instance objects for uninitialized linked rows. However, these objects do not have document IDs since the linked documents do not exist yet. But they always have link type as it must already exist.
=> Fix uninitialized link instance permissions #LMR-1666

src/app/core/rest/view.service.ts, src/app/core/store/views/views.effects.ts
We should make all services stateless in the future. Even `organizationId` and `projectId` should always be passed as arguments of their methods. Otherwise, we will encounter problems like this as the application keeps growing and becomes more complicated.
=> Fix sharing view in search perspective #LMR-1690

src/app/core/pusher/pusher.service.ts, src/app/core/rest/document.service.ts, src/app/core/store/collections/collection.util.ts, src/app/core/store/documents/documents.action.ts, src/app/core/store/documents/documents.effects.ts, src/app/core/store/link-instances/link-instances.action.ts, src/app/core/store/link-instances/link-instances.effects.ts, src/app/core/store/store.utils.ts, src/app/core/store/tables/tables.effects.ts, src/app/shared/data-input/files/files-data-input.component.ts, src/app/shared/utils/data/has-files-attribute-changed.ts
* use duplicate endpoint to clone primary document
* reload file attachments on document changes
* reload file attachments on link instance changes
* prevent multiple file attachment reloads
=> Keep file attachments up to date #LMR-1969

.circleci/config.yml
* use Debian 10 "Buster" which comes with git version 2.20
=> Fix old version of Git in CircleCI
