Lumeer/web-ui

- src/main/scripts/data/chat.json
- src/main/scripts/data/history.json
- src/main/scripts/src/app.module.ts
- src/main/scripts/src/components/views/query/document-info.component.ts
- src/main/scripts/src/components/views/query/document-preview.component.ts
- src/main/scripts/src/components/views/single_document/history-chat.component.html
- src/main/scripts/src/components/views/single_document/history-chat.component.scss
- src/main/scripts/src/components/views/single_document/history-chat.component.ts
- src/main/scripts/src/components/views/single_document/single-document.component.html
- src/main/scripts/src/components/views/single_document/single-document.component.ts
- src/main/scripts/src/components/views/views.module.ts
- src/main/scripts/src/services/document.service.ts
- src/main/scripts/src/services/index.ts
- src/main/scripts/src/services/navigation-children.service.ts
- src/main/scripts/src/styles/basic.scss
- src/main/scripts/src/viewport/left-panel.component.html
- src/main/scripts/src/viewport/left-panel.component.ts
Refactored how current document is stored in local storage.
> Make chat and history for document sticky

- src/main/scripts/src/components/views/query/document-info.component.html
- src/main/scripts/src/components/views/query/document-info.component.scss
Add nicer scroll to document preview.
> Enable nice scrollbar in document values

- src/main/scripts/src/components/common/common-components.module.ts
- src/main/scripts/src/components/common/tag-input/autocomplete-interface.ts
- src/main/scripts/src/components/common/tag-input/filter-input.component.html
- src/main/scripts/src/components/common/tag-input/filter-input.component.scss
- src/main/scripts/src/components/common/tag-input/filter-input.component.ts
- src/main/scripts/src/components/common/tag-input/tag-actions.ts
- src/main/scripts/src/components/common/tag-input/tag-input.component.html
- src/main/scripts/src/components/common/tag-input/tag-input.component.scss
- src/main/scripts/src/components/common/tag-input/tag-input.component.ts
- src/main/scripts/src/services/breadcrumb.service.ts
Now the input is seperate component, so we can use autocomplete input wherever we want.
> Remove input from from tag-input component

- src/main/scripts/src/components/common/common-components.module.ts
- src/main/scripts/src/components/common/tag-input/filter-input.component.ts
- src/main/scripts/src/components/common/tag-input/filter-save.component.html
- src/main/scripts/src/components/common/tag-input/filter-save.component.scss
- src/main/scripts/src/components/common/tag-input/filter-save.component.ts
- src/main/scripts/src/components/common/tag-input/tag-input.component.html
- src/main/scripts/src/components/common/tag-input/tag-input.component.ts
- src/main/scripts/src/components/views/collections/collection-add.component.ts
- src/main/scripts/src/components/views/pick_item/document-detail.component.ts
- src/main/scripts/src/components/views/pick_item/pick-item.component.ts
- src/main/scripts/src/components/views/pick_item/tabular-result.component.ts
- src/main/scripts/src/components/views/research/research.component.html
- src/main/scripts/src/components/views/research/research.component.scss
- src/main/scripts/src/components/views/research/research.component.ts
- src/main/scripts/src/components/views/views.module.ts
- src/main/scripts/src/services/document-info.service.ts
- src/main/scripts/src/viewport/content.component.html
- src/main/scripts/src/viewport/left-panel.component.ts
- src/main/scripts/src/viewport/top-panel.component.html
- src/main/scripts/src/viewport/top-panel.component.scss
- src/main/scripts/src/viewport/top-panel.component.ts
- src/main/scripts/src/viewport/viewport.component.html
- src/main/scripts/src/viewport/viewport.component.ts
No need to have filter in each component, so we'll make it standalone and use it where we want it.
> Make filter to be standalone

- src/main/scripts/data/documentpreview.json
- src/main/scripts/src/components/common/auto-complete/auto-complete.component.ts
- src/main/scripts/src/components/common/tag-input/filter-input.component.ts
- src/main/scripts/src/components/common/tag-input/filter.component.ts
- src/main/scripts/src/components/views/pick_item/tabular-result.component.ts
- src/main/scripts/src/components/views/research/document-content.component.ts
- src/main/scripts/src/components/views/research/document-post-it.component.html
- src/main/scripts/src/components/views/research/document-post-it.component.scss
- src/main/scripts/src/components/views/research/document-post-it.component.ts
- src/main/scripts/src/components/views/research/document-preview.component.html
- src/main/scripts/src/components/views/research/document-preview.component.scss
- src/main/scripts/src/components/views/research/document-preview.component.ts
- src/main/scripts/src/components/views/research/research.component.ts
- src/main/scripts/src/services/document-info.service.ts
- src/main/scripts/src/styles/basic.scss
style document details to be more consistent
> Add Option to select collection when adding new document

- src/main/scripts/src/app.module.ts
- src/main/scripts/src/boot.ts
- src/main/scripts/src/services/index.ts
- src/main/scripts/src/services/keycloak-http.service.ts
- src/main/scripts/src/services/keycloak.service.ts
Keycloak changed JS api and application kept refreshing, because keycloak checks for SSO and if none found it will keep refreshing.
> Fix keycloak refresh

- src/main/scripts/package.json
- src/main/scripts/src/app.module.ts
- src/main/scripts/src/components/views/research/empty-result.component.html
- src/main/scripts/src/components/views/research/empty-result.component.scss
- src/main/scripts/src/components/views/research/empty-result.component.ts
- src/main/scripts/src/components/views/views.module.ts
- src/main/scripts/src/services/collection.service.ts
- src/main/scripts/src/services/keycloak.service.ts
- src/main/scripts/src/vendor.ts
> Add all font awesome icons

- src/main/scripts/src/app/app.module.ts
- src/main/scripts/src/app/core/core.module.ts
- src/main/scripts/src/app/core/rest/collection.service.ts
- src/main/scripts/src/app/core/rest/document.service.ts
- src/main/scripts/src/app/search/all/search-all.component.html
- src/main/scripts/src/app/search/all/search-all.component.ts
- src/main/scripts/src/app/search/collections/collections-search.component.html
- src/main/scripts/src/app/search/collections/collections-search.component.ts
- src/main/scripts/src/app/search/documents/documents-search.component.html
- src/main/scripts/src/app/search/documents/documents-search.component.ts
- src/main/scripts/src/app/search/search-routing.module.ts
- src/main/scripts/src/app/search/search.component.html
- src/main/scripts/src/app/search/search.component.ts
- src/main/scripts/src/app/search/search.module.ts
- src/main/scripts/src/app/shared/perspectives/collections/collections-perspectives.module.ts
- src/main/scripts/src/app/shared/perspectives/collections/post-it/post-it-collections-perspective.component.html
- src/main/scripts/src/app/shared/perspectives/collections/post-it/post-it-collections-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/documents/documents-perspective.ts
- src/main/scripts/src/app/shared/perspectives/documents/documents-perspectives.module.ts
- src/main/scripts/src/app/shared/perspectives/documents/post-it/post-it-documents-perspective.component.html
- src/main/scripts/src/app/shared/perspectives/documents/post-it/post-it-documents-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/documents/table/table-documents-perspective.component.html
- src/main/scripts/src/app/shared/perspectives/documents/table/table-documents-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/perspective.directive.ts
- src/main/scripts/src/app/shared/perspectives/perspective.ts
- src/main/scripts/src/app/shared/perspectives/perspectives.module.ts
- src/main/scripts/tslint.json
You can try it by accessing the following address:
http://localhost:7000/ui/w/LMR/devel/search/documents?perspective=Table&query=something
> Draft perspectives structure and usage #LMR-214

- src/main/scripts/src/app/app.module.ts
- src/main/scripts/src/app/documents/documents-routing.module.ts
- src/main/scripts/src/app/documents/documents.module.ts
- src/main/scripts/src/app/documents/list/documents-list.component.html
- src/main/scripts/src/app/documents/list/documents-list.component.ts
- src/main/scripts/src/app/shared/perspectives/documents/documents-perspective-presenter.ts
- src/main/scripts/src/app/shared/perspectives/documents/documents-perspective.ts
- src/main/scripts/src/app/shared/perspectives/perspective-presenter.ts
I have prepared a documents module with a single component which makes use of perspectives. Some refactoring was needed in order to prevent code repetition.
> Prepare documents module #LMR-241

- src/main/scripts/src/app/app-routing.module.ts
- src/main/scripts/src/app/app.component.ts
- src/main/scripts/src/app/core/core.module.ts
- src/main/scripts/src/app/core/home.component.ts
I have tried different approaches including resolver and this one seems to be the easiest one. But feel free to propose a better approach.
> Redirect to search page if workspace is set #LMR-245

- src/main/scripts/src/app/app.component.scss
- src/main/scripts/src/app/core/core.module.ts
- src/main/scripts/src/app/core/dto/suggestion.ts
- src/main/scripts/src/app/core/header/header.component.html
- src/main/scripts/src/app/core/header/header.component.scss
- src/main/scripts/src/app/core/header/header.component.ts
- src/main/scripts/src/app/core/rest/search.service.ts
- src/main/scripts/src/app/shared/search-box/search-box.component.html
- src/main/scripts/src/app/shared/search-box/search-box.component.scss
- src/main/scripts/src/app/shared/search-box/search-box.component.ts
I have improved the search box to be able to suggest as well as build queries.
> Add search box with suggestions #LMR-179

- src/main/scripts/src/app/core/core.module.ts
- src/main/scripts/src/app/core/header/header.component.html
I suggest using the form [routerLink]="['path']" as it checks for imports.
> Fix link to workspace chooser #LMR-292

- README.md
As @marvec pointed out there is no mention about enviroments in README.
> Update readme about enviroments

- src/main/scripts/src/app/core/dto/document.ts
- src/main/scripts/src/app/core/rest/collection.service.ts
- src/main/scripts/src/app/core/rest/document.service.ts
- src/main/scripts/src/app/shared/perspectives/documents/documents-perspective.ts
- src/main/scripts/src/app/shared/perspectives/documents/documents-perspectives.module.ts
- src/main/scripts/src/app/shared/perspectives/documents/post-it/post-it-documents-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/documents/table/table-documents-perspective.component.html
- src/main/scripts/src/app/shared/perspectives/documents/table/table-documents-perspective.component.ts
- src/main/scripts/src/app/shared/table/event/data-event.ts
- src/main/scripts/src/app/shared/table/model/table-header-cell.ts
- src/main/scripts/src/app/shared/table/model/table-header.ts
- src/main/scripts/src/app/shared/table/model/table-row-cell.ts
- src/main/scripts/src/app/shared/table/model/table-row.ts
- src/main/scripts/src/app/shared/table/model/table-settings.ts
- src/main/scripts/src/app/shared/table/static-table/static-table.component.html
- src/main/scripts/src/app/shared/table/static-table/static-table.component.ts
- src/main/scripts/src/app/shared/table/static-table/table-header.component.html
- src/main/scripts/src/app/shared/table/static-table/table-header.component.ts
- src/main/scripts/src/app/shared/table/static-table/table-row.component.html
- src/main/scripts/src/app/shared/table/static-table/table-row.component.ts
Now it's possible to create document, update some value, add/remove/edit column through table perspective.
> Connect documents table with backend LMR-306

- src/main/scripts/src/app/core/dto/attribute.ts
- src/main/scripts/src/app/core/dto/document.ts
- src/main/scripts/src/app/core/dto/permission.ts
- src/main/scripts/src/app/core/dto/permissions.ts
- src/main/scripts/src/app/core/dto/query.ts
- src/main/scripts/src/app/core/dto/suggestions.ts
- src/main/scripts/src/app/core/dto/view.ts
- src/main/scripts/src/app/core/rest/collection.service.ts
- src/main/scripts/src/app/core/rest/document.service.ts
- src/main/scripts/src/app/core/rest/search.service.ts
- src/main/scripts/src/app/documents/list/documents-list.component.ts
- src/main/scripts/src/app/search/documents/documents-search.component.ts
- src/main/scripts/src/app/shared/permissions/role.ts
- src/main/scripts/src/app/shared/perspectives/collections/post-it/post-it-collections-perspective.component.html
- src/main/scripts/src/app/shared/perspectives/collections/post-it/post-it-collections-perspective.component.scss
- src/main/scripts/src/app/shared/perspectives/collections/post-it/post-it-collections-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/documents/post-it/document/post-it-document.component.ts
- src/main/scripts/src/app/shared/perspectives/documents/post-it/post-it-documents-perspective.component.html
- src/main/scripts/src/app/shared/perspectives/documents/post-it/post-it-documents-perspective.component.scss
- src/main/scripts/src/app/shared/perspectives/documents/post-it/post-it-documents-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/documents/table/table-documents-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/perspective-presenter.ts
- src/main/scripts/src/app/shared/perspectives/perspective.ts
- src/main/scripts/src/app/shared/search-box/search-box.component.ts
> Refactor perspectives to use searchService

- src/main/scripts/src/app/core/rest/collection.service.ts
- src/main/scripts/src/app/core/rest/search.service.ts
- src/main/scripts/src/app/shared/perspectives/collections/post-it/post-it-collections-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/documents/post-it/document/post-it-document.component.ts
> Fix search service paths

- src/main/scripts/src/app/shared/perspectives/collections/post-it/post-it-collections-perspective.component.html
- src/main/scripts/src/app/shared/perspectives/collections/post-it/post-it-collections-perspective.component.ts
> Fix document perspective path

- README.md
> Add How To Contribute section to Readme

- src/main/scripts/src/app/core/top-panel/top-panel.component.html
- src/main/scripts/src/app/core/top-panel/top-panel.component.scss
> Fix logo alignment in the top panel

- src/main/scripts/src/app/collection/list/collection-list.component.ts
- src/main/scripts/src/app/documents/list/documents-list.component.html
- src/main/scripts/src/app/documents/list/documents-list.component.ts
- src/main/scripts/src/app/search/results/all/all-search-results.component.html
- src/main/scripts/src/app/search/results/collections/collections-search-results.component.html
- src/main/scripts/src/app/search/results/collections/collections-search-results.component.ts
- src/main/scripts/src/app/search/results/documents/documents-search-results.component.html
- src/main/scripts/src/app/search/results/documents/documents-search-results.component.ts
- src/main/scripts/src/app/shared/perspectives/collections/collections-perspective-presenter.ts
- src/main/scripts/src/app/shared/perspectives/documents/documents-perspective-presenter.ts
- src/main/scripts/src/app/shared/perspectives/documents/documents-perspective.ts
- src/main/scripts/src/app/shared/perspectives/documents/documents-perspectives.module.ts
- src/main/scripts/src/app/shared/perspectives/documents/search/search-documents-perspective.component.html
- src/main/scripts/src/app/shared/perspectives/documents/search/search-documents-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/documents/table/table-documents-perspective.component.html
- src/main/scripts/src/app/shared/perspectives/documents/table/table-documents-perspective.component.ts
- src/main/scripts/src/app/shared/perspectives/perspective-choice.ts
- src/main/scripts/src/app/shared/perspectives/perspective-presenter.ts
- src/main/scripts/src/app/shared/perspectives/perspectives.module.ts
- src/main/scripts/src/app/shared/perspectives/shared/perspective-chooser/perspective-chooser.component.html
- src/main/scripts/src/app/shared/perspectives/shared/perspective-chooser/perspective-chooser.component.ts
> Enable users to switch perspectives #LMR-355

- src/main/scripts/src/app/app.component.ts
- src/main/scripts/src/app/core/top-panel/top-panel.component.ts
- src/main/scripts/src/app/shared/search-box/query-item/query-items-converter.ts
- src/main/scripts/src/app/shared/search-box/search-box.component.ts
- src/main/scripts/src/app/shared/utils/query-converter.ts
- src/main/scripts/src/app/shared/utils/route-finder.ts
When you enter a link containing a search query to the browser URL line and go to that page, the query will appear in the search bar as well.
> Fill search bar with items from query params #LMR-362

- src/main/scripts/package.json
- src/main/scripts/src/app/core/page-not-found/page-not-found.component.html
- src/main/scripts/src/app/core/search-home/search-home.component.html
- src/main/scripts/src/app/core/top-panel/top-panel.component.html
- src/main/scripts/src/app/core/top-panel/top-panel.component.ts
- src/main/scripts/src/app/shared/permissions/permissions.component.html
- src/main/scripts/src/app/shared/permissions/table/permissions-table.component.html
- src/main/scripts/src/app/shared/picker/color-picker/color-picker.component.html
- src/main/scripts/src/app/shared/post-it-collections/post-it-collections.component.html
- src/main/scripts/src/app/shared/post-it-collections/post-it-collections.component.ts
- src/main/scripts/src/app/shared/search-box/search-box.component.html
- src/main/scripts/src/app/shared/search-box/search-box.component.ts
- src/main/scripts/src/app/shared/table/static-table/table-header.component.html
- src/main/scripts/src/app/shared/utils/html-modifier.ts
- src/main/scripts/src/app/view/perspectives/post-it/add-document/add-document.component.html
- src/main/scripts/src/app/view/perspectives/post-it/document/post-it-document.component.html
- src/main/scripts/src/app/view/perspectives/post-it/post-it-perspective.component.html
- src/main/scripts/src/app/view/perspectives/search/search-perspective.component.html
- src/main/scripts/src/app/view/perspectives/table/table-perspective.component.html
- src/main/scripts/src/app/view/view-controls/share-dialog/share-dialog.component.html
- src/main/scripts/src/app/view/view-controls/share-dialog/share-dialog.component.ts
- src/main/scripts/src/app/view/view-controls/view-controls.component.html
- src/main/scripts/src/app/workspace/workspace-chooser/resource-chooser/resource-chooser.component.html
- src/main/scripts/src/app/workspace/workspace-chooser/resource-chooser/resource-chooser.component.ts
- src/main/scripts/src/app/workspace/workspace-chooser/workspace-chooser.component.html
- src/main/scripts/src/i18n/messages.sk.xlf
- src/main/scripts/src/i18n/messages.xlf
However, it is not possible to run the application with different languages at the moment. We need to figure out how to use `ng serve` and `ng build` commands which allow this.
> Prepare application for translation #LMR-364

- src/main/scripts/.angular-cli.json
* Remove component selector prefix
* Use .scss extension for styles
* Do not create test files
> Improve Angular CLI generate command defaults

- .travis.yml
- src/main/scripts/webpack.config.js
It was not possible to use AOT compilation before without specifying the language.
> Do not require locale for AOT compilation

- pom.xml
- src/main/scripts/src/app/core/top-panel/top-panel.component.html
This should finally fix the problem with logo.
I'm also adding AOT in production to see how it works on our servers.
> Fix logo and use AOT in production #LMR-416

- src/app/collection/config/collection-config.component.ts
- src/app/core/rest/document.service.ts
- src/app/view/perspectives/post-it/document-data/document-data.ts
- src/app/view/perspectives/post-it/post-it-perspective.component.ts
- Add missing RxJS operator imports
- Fix document service throwing error on document creation
> Fix multiple documents created on creation of single document

- src/app/collection/config/tab/link-types/collection-link-types.component.ts
- src/app/collection/constants.ts
- src/app/collection/service/collection-select.service.ts
- src/app/shared/post-it-collections/post-it-collections.component.ts
> Extract collection constants to separate file

- src/app/shared/post-it-collections/post-it-collection-data.ts
- src/app/shared/post-it-collections/post-it-collections.component.ts
> Fix creating multiple collections on creation of one

- src/app/shared/permissions/permissions.component.html
- src/app/shared/permissions/permissions.component.scss
- src/app/shared/permissions/table/permissions-table.component.html
- src/app/shared/permissions/table/permissions-table.component.scss
- src/app/shared/permissions/table/permissions-table.component.ts
> Redesign permissions table #LMR-400

- src/app/shared/common.scss
> Fix notification prompts and confirms not acting as modal

- package.json
* It brings official support for Angular 5.0
> Update ngx-contextmenu dependency version to 3.0.0

- src/app/view/perspectives/post-it/post-it-perspective.component.ts
- src/app/view/perspectives/search/search-perspective.component.ts
- src/app/view/perspectives/table/table-perspective.component.ts
It seems that AOT compilation cannot deal with recursively defined types.
> Fix perspective loading after AOT compilation #LMR-495

- src/app/shared/post-it-collections/post-it-collections.component.html
- src/app/shared/post-it-collections/post-it-collections.component.ts
- src/app/view/perspectives/search/collections/search-collections.component.html
- src/app/view/perspectives/search/collections/search-collections.component.ts
> Enable users to create collections #LMR-469

- src/app/collection/config/collection-config.component.ts
- src/app/collection/config/tab/link-types/collection-link-types.component.ts
- src/app/core/rest/collection.service.ts
- src/app/core/rest/home-page.service.ts
- src/app/core/rest/link-type.service.ts
- src/app/core/rest/search.service.ts
- src/app/core/rest/view.service.ts
- src/app/shared/post-it-collections/post-it-collections.component.html
- src/app/shared/post-it-collections/post-it-collections.component.ts
- src/app/shared/utils/post-it-layout.ts
- src/app/shared/utils/query-converter.ts
- src/app/view/perspectives/post-it/document-data/document-data.ts
- src/app/view/perspectives/post-it/document/post-it-document.component.html
- src/app/view/perspectives/post-it/document/post-it-document.component.ts
- src/app/view/perspectives/post-it/post-it-perspective.component.html
- src/app/view/perspectives/post-it/post-it-perspective.component.scss
- src/app/view/perspectives/post-it/post-it-perspective.component.ts
- src/app/view/perspectives/search/search-perspective.component.ts
> Optimize document post-its perspective, fix layout and add infinite scroll #LMR-476 #LMR-481 #LMR-468

- src/app/view/perspectives/search/search-perspective.component.html
- src/app/view/perspectives/table/table-perspective.component.html
- src/app/view/view.component.html
Every perspective now manages its width on its own.
> Manage view width by perspectives #LMR-531

- src/app/shared/post-it-collections/post-it-collections.component.html
> Fix color and icon choosing dropdown appears when navigating to collection documents

- src/app/collection/config/tab/attribute-list/attribute-list.component.html
- src/app/collection/config/tab/attribute-list/attribute-list.component.scss
- src/app/collection/config/tab/attribute-list/attribute-list.component.ts
- src/app/collection/config/tab/constraints.ts
- src/app/collection/config/tab/events/collection-events.component.html
- src/app/collection/config/tab/events/collection-events.component.scss
>  Improve constraint editing #LMR-477

- src/app/core/store/notifications/notifications.action.ts
- src/app/core/store/notifications/notifications.effects.ts
- src/app/core/store/smartdoc-templates/smartdoc-templates.action.ts
- src/app/core/store/smartdoc-templates/smartdoc-templates.effects.ts
- src/app/view/perspectives/smartdoc/document/smartdoc-document.component.ts
@justmesr, what do you think about this way of using the confirm dialog?
> Add smart document part deletion confirm dialog #LMR-555

- src/app/core/top-panel/top-panel.component.html
- src/app/core/top-panel/top-panel.component.scss
- src/app/core/top-panel/top-panel.component.ts
> Add home button #LMR-585

- README.md
- config/custom-plugins.js
- config/settings.js
- src/app/core/top-panel/top-panel.component.html
- src/app/core/top-panel/top-panel.component.ts
- src/app/custom-typings.d.ts
@marvec, you just need to set `BUILD_NUMBER` environment variable when building the project.
> Display build number in top panel menu #LMR-645

- src/app/view/perspectives/search/documents/search-documents.component.ts
It caused the previous problems as well and the root cause is probably NgRx bug.
> Fix fictional documents on search perspective #LMR-595

- src/app/view/perspectives/post-it/add-document/add-document.component.ts
- src/app/view/perspectives/post-it/document/post-it-document.component.ts
- src/app/view/perspectives/post-it/post-it-perspective.component.ts
> ui/w/$ORG/$PROJ/view/postit - new record should already contain existing attributes #LMR-600

- src/app/workspace/organization/groups/organization-groups.component.html
- src/app/workspace/organization/groups/organization-groups.component.ts
- src/app/workspace/organization/organization-settings.component.html
- src/app/workspace/organization/registration/organization-registration.component.html
- src/app/workspace/organization/registration/organization-registration.component.ts
- src/app/workspace/organization/users/organization-users.component.html
- src/app/workspace/organization/users/organization-users.component.ts
- src/app/workspace/workspace-routing.module.ts
- src/app/workspace/workspace.module.ts
> Set up user and group management routing #LMR-662

- src/app/collection/config/tab/attribute-list/attribute-list.component.html
- src/app/collection/config/tab/attribute-list/attribute-list.component.ts
- src/app/view/perspectives/post-it/document/post-it-document.component.html
- src/app/view/perspectives/post-it/document/post-it-document.component.ts
- src/app/view/perspectives/post-it/post-it-perspective.component.html
- src/app/view/perspectives/post-it/post-it-perspective.component.ts
> ui/w/$ORG/$PROJ/view/postit - attribute suggestion with correct case #LMR-601

- CONTRIBUTING.md
Add some reading references and briefly explain reusable component design.
> Update contributing guide #LMR-714

- src/app/view/perspectives/post-it/document/post-it-document.component.ts
I wasn't able to reproduce the issue. However I've found an issue that might have caused documents to be deleted before they even appeared. 
> ui/w/$ORG/$PROJ/view/postit - cannot add records to a new empty file #LMR-606

- src/app/view/perspectives/post-it/post-it-perspective.component.ts
- src/app/view/perspectives/post-it/util/selection-helper.ts
> ui/w/$ORG/$PROJ/view/postit - first enter values on new items #LMR-694

- src/app/view/perspectives/post-it/document/post-it-document.component.ts
- src/app/view/perspectives/post-it/post-it-perspective.component.ts
> ui/w/$ORG/$PROJ/view/postit - attribute order suddenly switched #LMR-695

- src/app/view/perspectives/post-it/document/post-it-document.component.html
- src/app/view/perspectives/post-it/document/post-it-document.component.scss
- src/app/view/perspectives/post-it/document/post-it-document.component.ts
- src/app/view/perspectives/search/documents/search-documents.component.scss
- src/app/view/perspectives/search/documents/search-documents.component.ts
Default attribute styles added.
Unified document view attribute and value styles.
Smart-doc attribute styles were left unchanged.
> ui/workspace/ - update attribute name styles throughout the app #LMR-701

- src/app/core/store/collections/collections.state.ts
- src/app/core/store/documents/documents.filters.ts
- src/app/shared/post-it-collections/post-it-collections.component.ts
- src/app/shared/search-box/search-box.component.ts
- src/app/view/perspectives/post-it/util/query-helper.ts
- src/app/view/perspectives/search/all/search-all.component.ts
Lesson learnt: Everything can be `null` or `undefined`.
> Fix errors on creating new view #LMR-728

- src/app/view/perspectives/post-it/document/post-it-document.component.html
- src/app/view/perspectives/post-it/document/post-it-document.component.scss
> ui/w/$ORG/$PROJ/view/postit - all long names must have tooltips #LMR-697

- src/app/workspace/workspace-chooser/resource-chooser/resource-chooser.component.scss
- src/app/workspace/workspace-chooser/resource-chooser/resource-chooser.component.ts
I also tried to fix overlapping picker, but I didn't find the correct way...
> ui/workspace - cannot go beyond the viewport #LMR-710

- src/app/core/top-panel/top-panel.component.html
- src/app/view/perspectives/search/search-perspective.component.html
- src/app/view/perspectives/search/search-perspective.component.ts
Bug caused by routerLinkActive checking for queryParams. 
Added new function to manually check if proper route was activated.
> [Lmr-699] Fix

- src/app/shared/placeholder/remove-placeholder-on-focus.ts
- src/app/shared/shared.module.ts
- src/app/view/perspectives/post-it/document/post-it-document.component.html
- src/app/view/perspectives/post-it/document/post-it-document.component.ts
- src/app/view/perspectives/post-it/post-it-perspective.component.ts
> Fix no plus sign and tab navigation #LMR-599 #LMR-734

- src/app/collection/config/tab/attribute-list/attribute-list.component.html
> Fix attribute delete icon

- src/app/collection/config/tab/attribute-list/attribute-list.component.html
- src/app/collection/config/tab/attribute-list/attribute-list.component.ts
It was impossible to create new attributes in collection config.
> Fix inability to create attributes

- src/app/shared/post-it-collections/post-it-collections.component.html
- src/app/shared/post-it-collections/post-it-collections.component.scss
- src/app/shared/post-it-collections/post-it-collections.component.ts
- src/app/view/perspectives/post-it/document/post-it-document.component.html
- src/app/view/perspectives/post-it/document/post-it-document.component.ts
- src/app/view/perspectives/post-it/post-it-perspective.component.html
Fix error on name unfocus and different post-it heights.
> Fix issues with collections

- src/app/core/rest/search.service.ts
- src/app/core/store/views/view.filters.ts
- src/app/shared/utils/array.utils.ts
- src/app/view/perspectives/search/documents/search-documents.component.html
- src/app/view/perspectives/search/documents/search-documents.component.ts
- src/app/view/view-controls/view-controls.component.ts
…ils for individual records #LMR-782
>  search/records - no data are loaded at first, then cannot unfold details for individual records #LMR-782

- src/app/core/top-panel/top-panel.component.html
- src/app/core/top-panel/top-panel.component.ts
* show organization and project name on hover
* prevent page reload on logo click
* remove license info from dropdown menu
> Fix top panel issues #LMR-775 #LMR-833 #LMR-842

- src/app/view/perspectives/search/all/search-all.component.html
- src/app/view/perspectives/search/views/search-views.component.ts
> Add views to search all perspective

- src/app/view/perspectives/post-it/add-document/add-document.component.html
> Fix add document button missing onClick

- src/app/workspace/workspace-chooser/resource-chooser/resource-chooser.component.html
- src/app/workspace/workspace-chooser/resource-chooser/resource-chooser.component.scss
- src/app/workspace/workspace-chooser/resource-chooser/resource-chooser.component.ts
It's not a perfect solution but most use cases should be covered.
> Fix icon picker z-index on workspace page #LMR-682

- package-lock.json
- package.json
- src/app/view/perspectives/chart/chart-perspective-routing.module.ts
- src/app/view/perspectives/chart/visualizer/line-visualizer.ts
- src/app/view/perspectives/post-it/post-it-perspective-routing.module.ts
- src/app/view/perspectives/post-it/post-it-perspective.module.ts
- src/app/view/perspectives/search/search-perspective-routing.module.ts
- src/app/view/perspectives/smartdoc/smartdoc-perspective-routing.module.ts
- src/app/view/perspectives/smartdoc/smartdoc-perspective.module.ts
- src/app/view/perspectives/table2/table-perspective-routing.module.ts
- src/app/view/perspectives/table2/table2-perspective.module.ts
- src/app/view/view-routing.module.ts
- src/app/view/view.module.ts
- src/polyfills.ts
- webpack.config.js
It works even without Angular CLI and splits libraries between chunks as well.
Some tweak will probably be needed in the future but the application loads 2x faster now.
> Turn on perspective modules lazy loading #LMR-491

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/core/core.module.ts
- src/app/core/error/raven-error.handler.ts.ts
Please have a look at package-lock.json. Created with npm@5.6.0
> Add sentry error monitoring

- package-lock.json
- package.json
- src/app/core/top-panel/top-panel.component.html
- src/app/shared/common.scss
- src/app/shared/language/chooser/language-chooser.component.html
- src/app/shared/language/chooser/language-chooser.component.scss
- src/app/shared/language/chooser/language-chooser.component.ts
- src/app/shared/language/language-link.pipe.ts
- src/app/shared/language/language.module.ts
- src/app/shared/language/language.ts
- src/app/shared/shared.module.ts
These changes enable users to switch between languages from the menu:
> Enable language switching by users #LMR-855

- src/app/app.component.html
- src/app/app.component.ts
- src/app/auth/auth-routing.module.ts
- src/app/auth/callback/auth-callback.component.html
- src/app/auth/callback/auth-callback.component.scss
- src/app/auth/callback/auth-callback.component.ts
- src/app/core/store/users/users.action.ts
- src/app/core/store/users/users.effects.ts
- src/app/core/store/users/users.reducer.ts
- src/app/core/store/users/users.state.ts
It was caused by previous auth redirect fix.
> Fix double user login #LMR-1071

- src/app/auth/callback/auth-callback.component.html
- src/app/auth/callback/auth-callback.component.scss
- src/app/auth/callback/auth-callback.component.ts
- src/app/shared/top-panel/wrapper/top-panel-wrapper.component.scss
- src/i18n/messages.cs.xlf
- src/i18n/messages.en.xlf
- src/i18n/messages.xlf
Update design of auth callback page, update animation timing and fix browser warning computation
> Update of auth-callback page visuals

- src/app/shared/document-hints/document-hints.component.scss
> Fix hidden document hints on bottom of screen #LMR-1106

- src/app/collection/collection-settings.guard.ts
- src/app/collection/settings/tab/attributes/collection-attributes.component.html
- src/i18n/messages.cs.xlf
- src/i18n/messages.en.xlf
- src/i18n/messages.xlf
Fix LMR-1126 - collection settings guard, fix translations, fix duplicate translation string reference
> Fix collection settings guard #LMR-1126

- src/app/core/store/navigation/navigation.effects.ts
- src/app/workspace/organization/organization-settings.guard.ts
- src/app/workspace/project/project-settings.guard.ts
Fix back button in resource header, fix redirect of guards in case of an error
> Fix back button in resource header #LMR-1127

- src/app/core/store/tables/table.converter.ts
- src/app/shared/pipes/colors.pipe.ts
- src/app/shared/pipes/icons.pipe.ts
Not fixing those that have deeper roots and would just hide the real cause.
> Fix some errors from Sentry #LMR-1161

- cypress/support/commands.js
Now it waits 30 seconds for auth token to arrive.
> Fix failing Cypress tests #LMR-1163

- package-lock.json
- package.json
- src/polyfills.ts
It fixes rendering of table rows in Safari.
> Add polyfill for IntersectionObserver #LMR-1196

- package.json
- src/app/shared/utils/string.utils.spec.ts
- src/app/shared/utils/string.utils.ts
Fixes [LUMEERIO-5D](https://sentry.io/answer-institute-sro/lumeerio/issues/762469919/) from Sentry.
> Escape string for regex in HighlightTextPipe #LMR-1241

- .circleci/config.yml
- .travis.yml
- angular.json
- package-lock.json
- package.json
- src/app/core/store/charts/charts.state.ts
- src/app/core/store/collections/collections.state.ts
- src/app/core/store/common/permissions.selectors.ts
- src/app/core/store/documents/documents.state.ts
- src/app/core/store/groups/groups.state.ts
- src/app/core/store/link-instances/link-instances.state.ts
- src/app/core/store/link-types/link-types.state.ts
- src/app/core/store/maps/maps.state.ts
- src/app/core/store/navigation/navigation.state.ts
- src/app/core/store/organizations/contact/contacts.state.ts
- src/app/core/store/organizations/organizations.state.ts
- src/app/core/store/organizations/payment/payments.state.ts
- src/app/core/store/organizations/service-limits/service-limits.state.ts
- src/app/core/store/postit/postit.state.ts
- src/app/core/store/projects/projects.state.ts
- src/app/core/store/tables/tables.selector.ts
- src/app/core/store/tables/tables.state.ts
- src/app/core/store/users/users.state.ts
- src/app/core/store/views/views.state.ts
- src/app/shared/post-it-collections/import-button/post-it-collection-import-button.component.ts
- src/app/view/perspectives/map/content/render/map-tiles.ts
- travis.sh
* update all other depdendencies (except for D3 types)
* use Node.js 10 (LTS) in CI (oficially supported by Angular now)
> Upgrade to Angular 7.1 #LMR-1218

- src/app/collection/settings/tab/attributes/collection-attributes.component.ts
- src/app/core/model/data/column-function.ts
- src/app/core/model/data/constraint.ts
- src/app/core/model/data/data-value.ts
- src/app/core/store/collections/collection.converter.ts
- src/app/core/store/collections/collection.model.ts
- src/app/core/store/documents/document.converter.ts
- src/app/core/store/documents/document.model.ts
- src/app/core/store/documents/documents.filters.spec.ts
- src/app/core/store/link-types/link-type.model.ts
- src/app/core/store/tables/tables.effects.ts
- src/app/core/ui/document-ui.ts
- src/app/view/perspectives/table/body/rows/cell-group/data-cell/table-data-cell.component.ts
- src/app/view/perspectives/table/header/column-group/single-column/attribute-suggestions/table-attribute-suggestions.component.ts
- src/app/view/perspectives/table/header/column-group/single-column/table-single-column.component.ts
@marvec @kubedo8 I have prepared interfaces for constraints. Please, check if this is the way we want to work with them.
> Prepare constraint interfaces #LMR-1281

- src/app/shared/post-it-collections/post-it-collection.component/post-it-collection.component.html
Fixes [LUMEERIO-5Z](https://sentry.io/answer-institute-sro/lumeerio/issues/841610579/)
> Fix icon picker in collection post-it #LMR-1372

- src/app/core/rest/interceptors/sentry.http-interceptor.ts
> Fix reporting HTTP errors to Sentry #LMR-1443

- cypress/integration/perspective/table/table-perspective-single-cell.js
- src/app/shared/data-input/text/text-data-input.component.ts
- src/app/shared/key-code.ts
- src/app/view/perspectives/table/body/rows/cell-group/data-cell/table-data-cell.component.html
- src/app/view/perspectives/table/header/hidden-input/table-hidden-input.component.html
* add single table cell E2E test
> Fix undefined value in empty table cell #LMR-1444

- src/app/app.component.ts
- src/app/core/store/collections/collections.effects.ts
- src/app/core/store/organizations/payment/payments.effects.ts
- src/app/core/store/users/users.effects.ts
- src/app/core/store/views/views.effects.ts
- src/app/dialog/dialog/feedback-dialog.component.ts
- src/app/dialog/share-view/share-view-dialog.component.ts
- src/index.html
> Set Google Analytics events and advanced dimensions reporting #LMR-1740

- src/app/shared/document-hints/can-show-attribute-hints.pipe.ts
- src/app/shared/document-hints/document-hints.component.html
- src/app/shared/document-hints/document-hints.component.ts
- src/app/view/perspectives/table/body/rows/cell-group/data-cell/table-data-cell.component.html
- src/app/view/perspectives/table/body/rows/cell-group/data-cell/table-data-cell.component.ts
* copy previous link data
* delete previous document with empty data
> Fix document hints in initialized table row #LMR-1766

- src/app/view/perspectives/table/header/column-group/single-column/attribute-suggestions/table-attribute-suggestions.component.html
- src/app/view/perspectives/table/header/column-group/single-column/attribute-suggestions/table-attribute-suggestions.component.ts
- src/app/view/perspectives/table/header/column-group/single-column/table-single-column.component.html
* fix reacting to table column input changes
* fix navigating in suggestions by keyboard
> Fix table attribute suggestions #LMR-1754

- package-lock.json
- package.json
- src/app/core/store/geocoding/geocoding.action.ts
- src/app/core/store/geocoding/geocoding.effects.ts
- src/app/core/store/geocoding/geocoding.reducer.ts
- src/app/core/store/geocoding/geocoding.state.ts
- src/app/core/store/maps/map.model.ts
- src/app/shared/data-input/address/address-data-input.component.ts
- src/app/shared/data-input/coordinates/coordinates-data-input.component.ts
- src/app/shared/utils/data.utils.ts
- src/app/shared/utils/map/coordinates.utils.ts
- src/app/view/perspectives/map/content/map-content.component.html
- src/app/view/perspectives/map/content/map-content.component.ts
- src/app/view/perspectives/map/content/map-content.utils.ts
- src/app/view/perspectives/map/content/render/map-render.component.scss
- src/app/view/perspectives/map/content/render/map-render.component.ts
- src/app/view/perspectives/map/content/render/map-render.utils.ts
- src/app/view/perspectives/map/content/render/marker-move-event.ts
* sync RxJS version with Angular
> Make map markers editable #LMR-1796

- src/app/dialog/attribute-type/form/constraint-config/coordinates/coordinates-constraint-config-form.component.html
- src/app/dialog/attribute-type/form/constraint-config/coordinates/coordinates-constraint-config-form.component.ts
> Limit precision in coordinates config #LMR-1860

- src/app/view/perspectives/map/content/render/map-render.utils.ts
> Show address or coordinates in map marker popup #LMR-1939

- src/app/shared/data-input/files/dropdown/files-dropdown.component.html
- src/app/shared/data-input/files/dropdown/files-dropdown.component.ts
> Simplify browse button in files dropdown #LMR-1941

- package-lock.json
- src/app/shared/data-input/files/button/file-attachment-button.component.ts
- src/app/shared/data-input/files/dropdown/files-dropdown.component.ts
- src/app/shared/data-input/files/files-data-input.component.ts
- src/app/shared/top-panel/top-panel.component.html
- src/app/shared/top-panel/user-panel/user-menu/user-menu.component.ts
- src/app/shared/top-panel/user-panel/user-panel.component.html
- src/app/shared/top-panel/user-panel/user-panel.component.ts
- src/app/view/perspectives/pivot/wrapper/config/pivot-config-wrapper.component.html
- src/app/view/perspectives/search/all/empty-data/empty-data.component.html
- src/app/view/perspectives/search/all/search-all.component.html
- src/app/view/perspectives/search/views/search-views.component.html
- src/app/view/perspectives/search/views/search-views.component.scss
- src/app/view/view-controls/view-controls.component.html
- src/i18n/messages.cs.xlf
- src/i18n/messages.en.xlf
- src/i18n/messages.xlf
- src/styles.scss
> Rename Kanban to Board, update app tour, complete translations, minor style fixes #LMR-1950

- src/app/core/model/data-value/text.data-value.ts
- src/app/shared/document-hints/document-hints.component.ts
- src/app/shared/pipes/highlight-text.pipe.ts
- src/app/shared/utils/string.utils.ts
- src/app/view/perspectives/calendar/util/calendar-converter.ts
- src/app/view/perspectives/gantt-chart/util/gantt-chart-converter.ts
> Fix documents hints in Text constraint; fix colors in gantt & calendar #LMR-2266

- src/app/core/store/common/permissions.selectors.ts
- src/app/core/validators/custom-validators.ts
- src/app/shared/data-resource/detail/links-toolbar/links-toolbar.component.ts
- src/app/shared/modal/attribute-type/attribute-type-modal.component.html
- src/app/shared/modal/create-link/create-link-modal.component.html
- src/app/shared/modal/create-link/create-link-modal.component.ts
- src/app/shared/modal/create-link/link-name-input/link-name-input.component.html
- src/app/shared/modal/modal.service.ts
- src/app/view/perspectives/table/header/add-button/table-header-add-button.component.ts
- src/app/view/perspectives/table/header/column-group/single-column/attribute-suggestions/table-attribute-suggestions.component.ts
> Prevent creating link types with duplicate names between the same collections

- src/app/shared/table/table.component.ts
…the space with Add new row button
> Close the detail panel in workspace when clicking under the table in the space with Add new row button
